### ISSUE TITLE
example script for multiple inserts inside inserts

### ISSUE THREAD

**Issue by avilella** [sbotond/phylosim#5]
Hi,
I would like to request an example script to simulate a sequence that will recursively accept insertions of the same template roughly at the center of the sequence, and those inserted sequences will incur in more insertions from the same template recursively.

PhyloSim For The Win!

**Comment by sbotond** [comment]
See commit: https://github.com/sbotond/phylosim/commit/bbe112dae861805e933304db65289c6665e1c2e8
